#!/bin/bash

# ==========================================
# CYBERPUNK THEME COLORS & STYLES
# ==========================================
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Clear screen for cinematic effect
clear

# ==========================================
# ASCII ART BANNER
# ==========================================
echo -e "${CYAN}${BOLD}"
cat << "EOF"
  ____ _   _ _____    _  _____       ___ ___ _____ 
 / ___| | | | ____|  / \|_   _|     / __|_ _|_   _|
| |   | |_| |  _|   / _ \ | | _____ \__ \| |  | |  
| |___|  _  | |___ / ___ \| | |_____|___/| |  | |  
 \____|_| |_|_____/_/   \_\_|       |___/___| |_|  
                                                   
EOF
echo -e "${NC}"

echo -e "${MAGENTA}[ SYS_INIT ]${NC} Booting installation sequence..."
sleep 0.6

# Variables
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
COMMAND_NAME="cheat-sit"
BIN_PATH="$BIN_DIR/$COMMAND_NAME"

# Locate Repo
echo -e "${CYAN}[ NETWORK ]${NC} Locating repository core at: ${YELLOW}$REPO_DIR${NC}"
sleep 0.5

# ==========================================
# DEPENDENCY CHECK (Advanced Feature)
# ==========================================
echo -e "${CYAN}[ SYSTEM ]${NC} Scanning for required dependencies..."
sleep 0.5
for cmd in git python3; do
    if command -v $cmd &> /dev/null; then
        echo -e "  ${GREEN}[+]${NC} $cmd : ${GREEN}ONLINE${NC}"
    else
        echo -e "  ${RED}[!]${NC} $cmd : ${RED}MISSING. Sequence aborted. Install $cmd first.${NC}"
        exit 1
    fi
    sleep 0.3
done

# Create Directory
if [ ! -d "$BIN_DIR" ]; then
    echo -e "${MAGENTA}[ FS_WRITE ]${NC} Constructing local binary sector: ${YELLOW}$BIN_DIR${NC}"
    mkdir -p "$BIN_DIR"
    sleep 0.4
fi

echo -e "${CYAN}[ SYNTHESIS ]${NC} Forging auto-updating executable payload..."
sleep 0.6

# ==========================================
# GENERATE THE BINARY
# ==========================================
cat > "$BIN_PATH" <<EOF
#!/bin/bash
# Auto-generated by CHEAT-SIT Cyberpunk Installer

# Access the core directory
cd "$REPO_DIR" || { echo -e "\033[0;31m[ FATAL ] Sector $REPO_DIR has vanished from the grid.\033[0m"; exit 1; }

# Stealth sync with the central mainframe (GitHub)
git pull origin main --quiet 2>/dev/null

# Execute the core payload
python3 cheat-sit.py "\$@"
EOF

# Grant execution rights
echo -e "${MAGENTA}[ OVERRIDE ]${NC} Bypassing security... Granting execution rights."
chmod +x "$BIN_PATH"
sleep 0.5

# ==========================================
# SUCCESS OUTRO
# ==========================================
<<<<<<< Updated upstream
echo ""
echo -e "${GREEN}${BOLD}[ UPLOAD COMPLETE ]${NC} ${CYAN}$COMMAND_NAME${NC} has been injected into your system."
echo -e "Deploy the tool anywhere in the grid by executing: ${YELLOW}${BOLD}$COMMAND_NAME${NC}"
echo ""
echo -e "${RED}[ WARNING ]${NC} If the terminal rejects the command, synchronize your neural pathways:"
echo -e "            ${BOLD}source ~/.bashrc${NC}  or  ${BOLD}source ~/.zshrc${NC}"
echo ""
=======
echo ""
echo -e "${GREEN}${BOLD}[ UPLOAD COMPLETE ]${NC} ${CYAN}$COMMAND_NAME${NC} has been injected into your system."
echo -e "Deploy the tool anywhere in the grid by executing: ${YELLOW}${BOLD}$COMMAND_NAME${NC}"
echo ""
echo -e "${RED}[ WARNING ]${NC} If the terminal rejects the command, synchronize your neural pathways:"
echo -e "            ${BOLD}source ~/.bashrc${NC}  or  ${BOLD}source ~/.zshrc${NC}"
echo ""
>>>>>>> Stashed changes
